### ISSUE TITLE
The code does not seem to work

### ISSUE THREAD

**Issue by Jichao-Peng** [el-cangrejo/3d_scene_segmentation#1]
I am a student from china, I tested your code recently, but It dose not seem to work, the origin image is all black and there is no segment result, I wander if you have finished this code? wish your relpy, thank you

**Comment by el-cangrejo** [comment]
Hi there, thanks for pointing it out. I've changed the code to work with depth images from the Kinect sensor.  I've tested it with images from this [dataset](https://data.acin.tuwien.ac.at/index.php/s/g3n3Uh31qi1sCH4) and it seems to work, although it needs some parameter tuning.

**Comment by Jichao-Peng** [comment]
It worked, thank you for your share!
